# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rfid_edit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.init = QtGui.QGroupBox(self.centralwidget)
        self.init.setGeometry(QtCore.QRect(10, 10, 981, 221))
        self.init.setObjectName(_fromUtf8("init"))
        self.btn_init = QtGui.QPushButton(self.init)
        self.btn_init.setGeometry(QtCore.QRect(50, 100, 121, 41))
        self.btn_init.setObjectName(_fromUtf8("btn_init"))
        self.table_init = QtGui.QTableView(self.init)
        self.table_init.setGeometry(QtCore.QRect(570, 10, 411, 211))
        self.table_init.setObjectName(_fromUtf8("table_init"))
        self.text_init = QtGui.QTextBrowser(self.init)
        self.text_init.setGeometry(QtCore.QRect(240, 20, 256, 192))
        self.text_init.setObjectName(_fromUtf8("text_init"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 240, 1001, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.btn_save = QtGui.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(860, 310, 111, 41))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.btn_read = QtGui.QPushButton(self.centralwidget)
        self.btn_read.setGeometry(QtCore.QRect(860, 430, 111, 41))
        self.btn_read.setObjectName(_fromUtf8("btn_read"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 300, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.edit_code = QtGui.QLineEdit(self.centralwidget)
        self.edit_code.setGeometry(QtCore.QRect(120, 299, 221, 21))
        self.edit_code.setObjectName(_fromUtf8("edit_code"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 360, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 360, 221, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 390, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 390, 221, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(500, 299, 221, 21))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 300, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 360, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(500, 360, 221, 91))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 260, 981, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox.raise_()
        self.init.raise_()
        self.line.raise_()
        self.btn_save.raise_()
        self.btn_read.raise_()
        self.label.raise_()
        self.edit_code.raise_()
        self.label_2.raise_()
        self.lineEdit_2.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.textEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_card = QtGui.QMenu(self.menubar)
        self.menu_card.setObjectName(_fromUtf8("menu_card"))
        self.menu_seting = QtGui.QMenu(self.menubar)
        self.menu_seting.setObjectName(_fromUtf8("menu_seting"))
        self.menu_about = QtGui.QMenu(self.menubar)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_connect = QtGui.QAction(MainWindow)
        self.action_connect.setObjectName(_fromUtf8("action_connect"))
        self.action_status = QtGui.QAction(MainWindow)
        self.action_status.setObjectName(_fromUtf8("action_status"))
        self.action_drive = QtGui.QAction(MainWindow)
        self.action_drive.setObjectName(_fromUtf8("action_drive"))
        self.action_club = QtGui.QAction(MainWindow)
        self.action_club.setObjectName(_fromUtf8("action_club"))
        self.action_kill = QtGui.QAction(MainWindow)
        self.action_kill.setObjectName(_fromUtf8("action_kill"))
        self.action_pass = QtGui.QAction(MainWindow)
        self.action_pass.setObjectName(_fromUtf8("action_pass"))
        self.action_help = QtGui.QAction(MainWindow)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_me = QtGui.QAction(MainWindow)
        self.action_me.setObjectName(_fromUtf8("action_me"))
        self.menu_card.addAction(self.action_connect)
        self.menu_card.addAction(self.action_status)
        self.menu_card.addSeparator()
        self.menu_card.addAction(self.action_drive)
        self.menu_seting.addAction(self.action_club)
        self.menu_seting.addSeparator()
        self.menu_seting.addAction(self.action_kill)
        self.menu_seting.addAction(self.action_pass)
        self.menu_about.addAction(self.action_help)
        self.menu_about.addSeparator()
        self.menu_about.addAction(self.action_me)
        self.menubar.addAction(self.menu_card.menuAction())
        self.menubar.addAction(self.menu_seting.menuAction())
        self.menubar.addAction(self.menu_about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "电子标签编辑器", None))
        self.init.setTitle(_translate("MainWindow", "初始化标签", None))
        self.btn_init.setText(_translate("MainWindow", "开始初始化", None))
        self.btn_save.setText(_translate("MainWindow", "保存", None))
        self.btn_read.setText(_translate("MainWindow", "查看", None))
        self.label.setText(_translate("MainWindow", "图书编码：", None))
        self.label_2.setText(_translate("MainWindow", "书架：", None))
        self.label_3.setText(_translate("MainWindow", "书格：", None))
        self.label_4.setText(_translate("MainWindow", "图书名称：", None))
        self.label_5.setText(_translate("MainWindow", "备注信息：", None))
        self.groupBox.setTitle(_translate("MainWindow", "编辑标签", None))
        self.menu_card.setTitle(_translate("MainWindow", "读卡器", None))
        self.menu_seting.setTitle(_translate("MainWindow", "设置", None))
        self.menu_about.setTitle(_translate("MainWindow", "关于", None))
        self.action_connect.setText(_translate("MainWindow", "连接", None))
        self.action_status.setText(_translate("MainWindow", "状态", None))
        self.action_drive.setText(_translate("MainWindow", "下载驱动", None))
        self.action_club.setText(_translate("MainWindow", "绘本馆", None))
        self.action_kill.setText(_translate("MainWindow", "灭活密码", None))
        self.action_pass.setText(_translate("MainWindow", "访问密码", None))
        self.action_help.setText(_translate("MainWindow", "帮助", None))
        self.action_me.setText(_translate("MainWindow", "作者", None))

